# TODO

db_settings:
  db_type: "sqlite"
  db_config:
    db_name: "db.sqlite3"

## Origin settings
twitter_auth_settings:
  load_from_file: true
  file_path: "./I-504/config/cookie/cookie_.json"

## Destination settings
misskey_auth_settings:
  load_from_file: true
  file_path: "./I-504/config/dest/misskey.yml"
