# TODO

db_settings:
  db_type: "sqlite"
  db_config:
    db_name: "db.sqlite3"

# Sources
source_list:
  twitter:
    enabled: true
    conf_path: "I-504/config/source/twitter.yml"
  test:
    enabled: false
    conf_path: "I-504/config/source/test.yml"

# Destinations
dest_list:
  misskey:
    enabled: true
    conf_path: "I-504/config/dest/misskey.yml"

